name = "hexcasting"
author = "Lemox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "260a7192e581ed3ec2db11f1bc07d0d35aa27d667f043c84a916ef74a4a59622"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
