name = "hexcasting"
author = "Lemox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ca9462fb45fecacd72124e7e0c1295c4f15d7fa39f772dbd6d1b8ff510d74e4"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
