name = "hexcasting"
author = "Lemox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36c86ae92638a0a2333cd651d59f52bdc25bebcae2863ee75db50ba5ac2e860e"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
